# Upptime config file
# See https://upptime.js.org/docs/configuration
owner: zinc-email
repo: upptime

sites:
  - name: Zinc Website
    url: https://zinc.email/
  - name: Zinc MTA (submission)
    url: mail.zinc.email
    port: 587
    check: "tcp-ping"

status-website:
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Zinc Email** protects your inbox from spam, malware, and phishing."
  introMessage: This page monitors the uptime and status of our services.
  navbar:
    - title: Status
      href: /
    - title: Zinc Email
      href: https://zinc.email/
  theme: night
