# Upptime config file
# See https://upptime.js.org/docs/configuration
owner: zinc-email
repo: upptime

sites:
  - name: Zinc Website
    url: https://zinc.email/
  - name: Zinc MTA (submission)
    check: "tcp-ping"
    port: 587
    url: mail.zinc.email

status-website:
  baseUrl: /upptime
  introTitle: "**Zinc Email** protects your inbox from spam, malware, and phishing."
  introMessage: This page monitors the uptime and status of our services.
  logoUrl: https://raw.githubusercontent.com/zinc-email/upptime/master/assets/zinc-icon.svg
  name: Upptime
  navbar:
    - title: Zinc Email
      href: https://zinc.email/
    - title: Status
      href: /
  theme: night
